### ISSUE TITLE
Leap year

### ISSUE THREAD

**Issue by MPavicevic** [kavvkon/enlopy#1]
How difficult would it be to generalize functions so that they are able to handle leap years. Lately I was using the tools for LDC analysis and it was almost impossible to deal with leap years. The only solution in my case was to get rid of 29.2. but this made may analysis less accurate.

**Comment by matteodefelice** [comment]
I don't know in detail the enlopy code, but why leap years should be important? In principle, you should be able to calculate a LDC on a set of *any* length...

**Comment by kavvkon** [comment]
Indeed I will include some leap year tests as well. In the initial design some routines where doing timeseries length checks, which may not be needed any more. It should be easy to fix I will check it soon

**Comment by kavvkon** [comment]
While I have spotted some ares to improve, @MPavicevic I tried quickly to reproduce your error but it worked fine:
```
import numpy as np; import enlopy as el                                                   
a = el.make_timeseries(np.random.randn(8784),year=2016,freq='h')
el.plot_LDC(a)
```
Could you provide an example ? Even try to save a dataframe as pickle and send it to me.

**Comment by MPavicevic** [comment]
Here is the example data frame, there are multiple years inside (2008 - 2013) it doesn't matter if I leave the nan values as they are or if i replace them with 0. I always get the same error message:

> Input vector length must be 12, 8760 or 35040. Otherwise freq has to be defined

I was using this code:

`el.plot_LDC(df['AT'], y_norm=False, stacked=False)`
  
[df.pkl.gz](https://github.com/kavvkon/enlopy/files/3818500/df.pkl.gz)

**Comment by kavvkon** [comment]
Yes your dataframe does not have a time index and the routine tries to infer the frequency from commonly known lengths. 8784 could be one of them indeed and I will try to make it more flexible in the future.
But you can solve the problem by putting a time index. You can use enlopy for that e.g.
>el.plot_LDC(el.make_timeseries(a,freq='h',year=2016), y_norm=False, stacked=False,alpha=.3,color='green')

**Comment by kavvkon** [comment]
The latest version should work regardless of the timeseries length
